package GraphDiagram.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Edge = 0;
  public static final int Graph = 1;
  public static final int Node = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xc0b03141f824430bL, 0xa88b4b8885d7ba65L);
    builder.put(0x51ac32e3792d17eeL, Edge);
    builder.put(0x51ac32e3792d17eaL, Graph);
    builder.put(0x51ac32e3792d17ebL, Node);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
