package GraphDiagram.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import jetbrains.mps.openapi.editor.descriptor.EditorHintsProvider;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorHint;
import java.util.Arrays;
import jetbrains.mps.editor.runtime.descriptor.ConceptEditorHintImpl;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase implements EditorHintsProvider {
  private Collection<ConceptEditorHint> myHints = Arrays.<ConceptEditorHint>asList(new ConceptEditorHintImpl("graphical", "", true, "GraphDiagram.editor.Graph.graphical"));
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Arrays.asList(new ConceptEditor[]{new Edge_Editor(), new Edge_graphical_Editor()});
      case 1:
        return Arrays.asList(new ConceptEditor[]{new Graph_Editor(), new Graph_graphical_Editor()});
      case 2:
        return Arrays.asList(new ConceptEditor[]{new Node_Editor(), new Node_graphical_Editor()});
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  public Collection<ConceptEditorHint> getHints() {
    return myHints;
  }


  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xc0b03141f824430bL, 0xa88b4b8885d7ba65L, 0x51ac32e3792d17eeL), MetaIdFactory.conceptId(0xc0b03141f824430bL, 0xa88b4b8885d7ba65L, 0x51ac32e3792d17eaL), MetaIdFactory.conceptId(0xc0b03141f824430bL, 0xa88b4b8885d7ba65L, 0x51ac32e3792d17ebL)).seal();
}
